config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  root 'car_logs#new'

  resources :cars, only: [:new, :create, :edit, :update, :index, :destroy] do
    member do
      get 'summary'
    end

    resources :fuels, only: [:create, :update, :destroy], controller: 'cars_fuels'
  end

  resources :car_logs, only: [:new, :create, :index, :show] do
    resources :refuels, only: [:new]
  end

  resources :fuels, only: [:new, :create, :edit, :update, :index, :destroy]

  resources :refuels, only: [:edit, :create, :update, :destroy]

  get '/login', to: 'sessions#new'
  match '/auth/:provider/callback', to: 'sessions#create', via: [:post, :get]
  get '/logout', to: 'sessions#destroy'
  get '/no_session', to: 'sessions#missing'
  get '/no_privileges', to: 'sessions#insufficient'
end

app/models/car_log.rb
# frozen_string_literal: true

class CarLog < ApplicationRecord
  belongs_to :car
  has_many :refuels

  accepts_nested_attributes_for :refuels
end

app/controllers/car_logs_controller.rb
# frozen_string_literal: true
class CarLogsController < ApplicationController
  HTML_DATETIME_LOCAL = '%Y-%m-%dT%H:%M:00'

  def new
    @default_time = Time.zone.now.strftime(HTML_DATETIME_LOCAL)
    car = Car.last
    @log = car.logs.build
    car.cars_fuels.manual_metering.each do |cf|
      @log.refuels.build(fuel_id: cf.fuel_id)
    end
  end

  def index
    @logs = CarLog.order(time: :desc).includes(refuels: :fuel).page(params[:page])
  end

  def show
    @log = CarLog.includes(refuels: :fuel).find(params[:id])
  end

  def create
    log = CarLog.new(car_log_params)
    fill_distance!(log)
    log.save

    if log.persisted?
      log.car.cars_fuels.automatic_metering.each do |cf|
        SyncRefuelFromMeterJob.perform_later(cf, log)
      end

      flash[:success] = I18n.t('flashs.created_model',
                               model: CarLog.model_name.human)
    else
      helpers.flash_errors(log.errors)
    end

    redirect_to action: :new
  end

  private

  def car_log_params
    params.require(:car_log).permit(:car_id, :time, :odometer, refuels_attributes: [:cost, :units_used, :fuel_id])
  end

  def fill_distance!(log)
    previous = log.car.logs.order(:time).where('time < ?', log.time).last
    previous_odo = previous ? previous.odometer : log.car.start_distance
    log.distance = log.odometer - previous_odo
  end
end

app/views/car_logs/index.html.haml
%h1= CarLog.model_name.human(count: 2)

%table.table
  %thead
    %tr
      %th= CarLog.human_attribute_name(:time)
      %th= CarLog.human_attribute_name(:distance)
      %th= Refuel.human_attribute_name(:units_used)
      %th= t('.consumption')
      %th= t('.cost_per_unit')
      %th= Refuel.human_attribute_name(:cost)

  - @logs.each do |log|
    - refuels_by_fuel = log.refuels.group_by(&:fuel)
    %tr
      %td= link_to l(log.time), car_log_path(log.id)
      %td= "#{human_number log.distance} km"
      %td
        - refuels_by_fuel.each do |fuel, refuels|
          .fuel-type= "#{human_number refuels.sum(&:units_used)} #{fuel.unit}"
      %td
        - refuels_by_fuel.each do |fuel, refuels|
          .fuel-type= "#{human_number(100 * refuels.sum(&:units_used) / log.distance)} #{fuel.unit}/100km"
      %td
        - refuels_by_fuel.each do |fuel, refuels|
          - if refuels.sum(&:units_used).zero?
            .fuel-type= "#{human_number(0.0, max_precision: 3)} €/#{fuel.unit}"
          - else
            .fuel-type= "#{human_number(refuels.sum(&:cost) / refuels.sum(&:units_used), max_precision: 3)} €/#{fuel.unit}"
      %td
        - refuels_by_fuel.each do |fuel, refuels|
          .fuel-type= "#{human_number refuels.sum(&:cost)} €"

= paginate(@logs)

app/views/car_logs/new.html.haml
.panel.panel-default
  .panel-heading
    = I18n.t('titles.new_model', model: CarLog.model_name.human)
  .panel-body
    = form_with model: @log, local: true do |f|
      .form-group
        = f.label :car_id
        = f.hidden_field :car_id
        .form-control-static= @log.car.name

      .form-group
        = f.label :time
        = f.text_field :time, class: 'form-control',
                              type: 'datetime-local',
                              value: @default_time

      .form-group
        = f.label :odometer
        .input-group
          .input-group-addon km
          = f.text_field :odometer, class: 'form-control', type: 'number', step: '0.1'

      = f.fields_for :refuels do |refuel_form|
        %h4= refuel_form.object.fuel.name

        = refuel_form.hidden_field :fuel_id
        .form-group
          = refuel_form.label :units_used
          .input-group
            .input-group-addon= refuel_form.object.fuel.unit
            = refuel_form.text_field :units_used, class: 'form-control', type: 'number', step: '0.01'

        .form-group
          = refuel_form.label :cost
          .input-group
            .input-group-addon €
            = refuel_form.text_field :cost, class: 'form-control', type: 'number', step: '0.01'

      = f.submit I18n.t('buttons.save'), class: 'btn btn-success'

app/views/car_logs/show.html.haml
.panel.panel-default
  .panel-heading
    = CarLog.model_name.human
  .panel-body
    %dl
      %dt= CarLog.human_attribute_name(:time)
      %dd= l(@log.time)

      %dt= CarLog.human_attribute_name(:odometer)
      %dd= "#{human_number @log.odometer} km"

      %dt= CarLog.human_attribute_name(:distance)
      %dd= "#{human_number @log.distance} km"
  %table.table
    %thead
      %tr
        %th= Refuel.human_attribute_name(:units_used)
        %th= t('.consumption')
        %th= t('.cost_per_unit')
        %th= Refuel.human_attribute_name(:cost)
        %th= I18n.t('action_column')

    - @log.refuels.each do |refuel|
      %tr
        %td= "#{human_number refuel.units_used} #{refuel.unit}"
        %td= "#{human_number(100 * refuel.units_used / @log.distance)} #{refuel.unit}/100km"
        %td
          - if refuel.units_used.zero?
            = "#{human_number(0.0, max_precision: 3)} €/#{refuel.unit}"
          - else
            = "#{human_number(refuel.cost / refuel.units_used, max_precision: 3)} €/#{refuel.unit}"
        %td= "#{human_number refuel.cost} €"
        %td
          %a.btn.btn-default{href: edit_refuel_path(refuel)}
            = I18n.t('buttons.edit')
  .panel-footer
    - @log.car.fuels.each do |fuel|
      %a.btn.btn-success{href: new_car_log_refuel_path(@log, fuel_id: fuel.id)}
        = I18n.t('buttons.refuel', fuel_name: fuel.name)