config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  root 'car_logs#new'

  resources :cars, only: [:new, :create, :edit, :update, :index, :destroy] do
    member do
      get 'summary'
    end

    resources :fuels, only: [:create, :update, :destroy], controller: 'cars_fuels'
  end

  resources :car_logs, only: [:new, :create, :index, :show] do
    resources :refuels, only: [:new]
  end

  resources :fuels, only: [:new, :create, :edit, :update, :index, :destroy]

  resources :refuels, only: [:edit, :create, :update, :destroy]

  get '/login', to: 'sessions#new'
  match '/auth/:provider/callback', to: 'sessions#create', via: [:post, :get]
  get '/logout', to: 'sessions#destroy'
  get '/no_session', to: 'sessions#missing'
  get '/no_privileges', to: 'sessions#insufficient'
end

app/models/refuel.rb
# frozen_string_literal: true

class Refuel < ApplicationRecord
  belongs_to :car_log
  belongs_to :fuel

  delegate :unit, to: :fuel
end

app/controllers/refuels_controller.rb
# frozen_string_literal: true
class RefuelsController < ApplicationController
  HTML_DATETIME_LOCAL = '%Y-%m-%dT%H:%M:00'

  def new
    @refuel = Refuel.new(car_log_id: params[:car_log_id], fuel_id: params[:fuel_id])

    render :edit
  end

  def edit
    @refuel = Refuel.find(params[:id])
  end

  def create
    refuel = Refuel.create(refuel_params)
    if refuel.persisted?
      flash[:success] = I18n.t('flashs.created_model',
                               model: Refuel.model_name.human)
    else
      helpers.flash_errors(refuel.errors)
    end

    redirect_to car_log_path(refuel.car_log_id)
  end

  def update
    refuel = Refuel.find(params[:id])
    if refuel.update(refuel_params)
      flash[:success] = I18n.t('flashs.updated_model',
                               model: Refuel.model_name.human)
    else
      helpers.flash_errors(refuel.errors)
    end

    redirect_to car_log_path(refuel.car_log_id)
  end

  def destroy
    refuel = Refuel.find(params[:id])
    refuel.destroy
    flash[:success] = I18n.t('flashs.destroyed_model',
                             model: Refuel.model_name.human)
    redirect_to car_log_path(refuel.car_log_id)
  end

  private

  def refuel_params
    params.require(:refuel).permit(:car_log_id, :fuel_id, :cost, :units_used)
  end
end

app/views/refuels/edit.html.haml
.panel.panel-default
  .panel-heading
    - if @refuel.new_record?
      = I18n.t('titles.new_model', model: Refuel.model_name.human)
    - else
      = I18n.t('titles.edit_model', model: Refuel.model_name.human)
  .panel-body
    = form_for @refuel do |f|
      = f.hidden_field :car_log_id
      = f.hidden_field :fuel_id

      .form-group
        = f.label :units_used
        .input-group
          .input-group-addon= f.object.fuel.unit
          = f.text_field :units_used, class: 'form-control', type: 'number', step: '0.01'

      .form-group
        = f.label :cost
        .input-group
          .input-group-addon €
          = f.text_field :cost, class: 'form-control', type: 'number', step: '0.01'

      = f.submit I18n.t('buttons.save'), class: 'btn btn-success'

- unless @refuel.new_record?
  .panel.panel-danger
    .panel-heading
      = I18n.t('titles.destroy_model', model: Refuel.model_name.human)
    .panel-body
      = link_to I18n.t('buttons.delete'), refuel_path(@refuel),
                method: :delete,
                class: 'btn btn-danger btn-sm',
                data: { confirm: I18n.t('confirm_delete_named', name: "#{@refuel.units_used} #{@refuel.unit}") }