config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  root 'car_logs#new'

  resources :cars, only: [:new, :create, :edit, :update, :index, :destroy] do
    member do
      get 'summary'
    end

    resources :fuels, only: [:create, :update, :destroy], controller: 'cars_fuels'
  end

  resources :car_logs, only: [:new, :create, :index, :show] do
    resources :refuels, only: [:new]
  end

  resources :fuels, only: [:new, :create, :edit, :update, :index, :destroy]

  resources :refuels, only: [:edit, :create, :update, :destroy]

  get '/login', to: 'sessions#new'
  match '/auth/:provider/callback', to: 'sessions#create', via: [:post, :get]
  get '/logout', to: 'sessions#destroy'
  get '/no_session', to: 'sessions#missing'
  get '/no_privileges', to: 'sessions#insufficient'
end

app/models/car.rb
# frozen_string_literal: true
class Car < ApplicationRecord
  has_many :logs, class_name: 'CarLog'
  has_many :refuels, through: :logs

  has_many :cars_fuels
  has_many :fuels, through: :cars_fuels

  validates :name, presence: true
  validates :start_date, presence: true
  validates :start_distance, presence: true
  validates :start_price, presence: true
end

app/controllers/cars_controller.rb
# frozen_string_literal: true
class CarsController < ApplicationController
  def new
    @car = Car.new
    render :edit
  end

  def edit
    @car = Car.find(params[:id])
  end

  def index
    @cars = Car.order(:start_date)
  end

  def create
    car = Car.create(car_params)
    if car.persisted?
      flash[:success] = I18n.t('flashs.created_model',
                               model: Car.model_name.human)
      redirect_to action: :edit, id: car.id
    else
      helpers.flash_errors(car.errors)
      redirect_to action: :index
    end
  end

  def update
    car = Car.find(params[:id])
    if car.update(car_params)
      flash[:success] = I18n.t('flashs.updated_model',
                               model: Car.model_name.human)
    else
      helpers.flash_errors(car.errors)
    end

    redirect_to action: :edit, id: car.id
  end

  def destroy
    Car.find(params[:id]).destroy
    flash[:success] = I18n.t('flashs.destroyed_model',
                             model: Car.model_name.human)
    redirect_to action: :index
  end

  def summary
    car = Car.includes(:logs).find(params[:id])
    @statistics = CarSummary.new(car)
  end

  private

  def car_params
    params.require(:car).permit(:name, :start_date, :start_price, :start_distance)
  end
end

app/views/cars/edit.html.haml
.panel.panel-default
  .panel-heading
    - if @car.new_record?
      = I18n.t('titles.new_model', model: Car.model_name.human)
    - else
      = I18n.t('titles.edit_model', model: Car.model_name.human)
  .panel-body
    = form_for @car do |f|
      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control'

      .form-group
        = f.label :start_distance
        = f.text_field :start_distance, class: 'form-control', type: :number

      .form-group
        = f.label :start_date
        = f.text_field :start_date, class: 'form-control', type: 'date'

      .form-group
        = f.label :start_price
        = f.text_field :start_price, class: 'form-control', type: :number

      = f.submit I18n.t('buttons.save'), class: 'btn btn-success'

- unless @car.new_record?
  .panel.panel-default
    .panel-heading
      = Fuel.model_name.human(count: 2)
    %table.table
      - @car.cars_fuels.includes(:fuel).each do |cf|
        %tr
          %td= cf.fuel.name
          %td
            - if cf.fuel.meterable?
              = form_with model: cf, url: car_fuel_path(id: cf.id, car_id: @car.id), method: 'patch', local: true, class: 'form-inline' do |f|
                .form-group
                  = f.label :meter_serial
                  = f.text_field :meter_serial, class: 'form-control'

                = f.submit I18n.t('buttons.save'), class: 'btn btn-success'
          %td= link_to I18n.t('buttons.delete'), car_fuel_path(id: cf.id, car_id: cf.car_id), method: :delete, class: 'btn btn-danger'
    .panel-footer
      = form_with url: car_fuels_path(car_id: @car.id), method: :post, local: true, class: 'form-inline' do |f|
        .form-group
          = f.label :fuel_id
          = f.collection_select :fuel_id, Fuel.all, :id, :name, {}, class: 'form-control'

        = f.submit I18n.t('buttons.add'), class: 'btn btn-success'


  .panel.panel-danger
    .panel-heading
      = I18n.t('titles.destroy_model', model: Car.model_name.human)
    .panel-body
      = link_to I18n.t('buttons.delete'), car_path(@car),
                method: :delete,
                class: 'btn btn-danger btn-sm',
                data: { confirm: I18n.t('confirm_delete_named', name: @car.name) }

app/views/cars/index.html.haml
%h1= Car.model_name.human(count: 2)

%table.table
  %thead
    %tr
      %th= Car.human_attribute_name(:name)
      %th= I18n.t('action_column')

  - @cars.each do |car|
    %tr
      %td= car.name
      %td
        %a.btn.btn-default{href: edit_car_path(car)}
          = I18n.t('buttons.edit')
        %a.btn.btn-primary{href: summary_car_path(car)}
          = t('.summary_button')

.row
  .col-md-2
    %a.btn.btn-success{href: new_car_path}
      = I18n.t('buttons.create_model', model: Car.model_name.human)

app/views/cars/summary.html.haml
%h1= t('.title', car: @statistics.car.name)

.row
  .col-md-6.col-sm-12
    .panel.panel-default
      .panel-heading
        = t('.totals_title')
      .panel-body
        %dl
          %dt= t('.distance')
          %dd= "#{human_number @statistics.logged_distance} km"
          %dt= t('.cost')
          - @statistics.logged_costs.each do |name, cost|
            %dd= "#{name}: #{human_number cost} €"
          %dt= t('.consumption')
          - @statistics.logged_consumptions.each do |fuel, units|
            %dd= "#{human_number units} #{fuel.unit}"
          %dt= t('.duration')
          %dd= "#{human_number @statistics.logging_duration} days"

.row
  .col-md-6.col-sm-12
    .panel.panel-default
      .panel-heading
        = t('.by_distance_title')
      .panel-body
        %dl
          %dt= t('.cost')
          - @statistics.costs_per_km.each do |name, cost_per_km|
            %dd= "#{name}: #{human_number(cost_per_km * 100)} ct/km"
          %dt= t('.consumption')
          - @statistics.consumptions_per_km.each do |fuel, consumption_per_km|
            %dd= "#{human_number consumption_per_km * 100} #{fuel.unit}/100 km"

  .col-md-6.col-sm-12
    .panel.panel-default
      .panel-heading
        = t('.by_time_title')
      .panel-body
        %dl
          %dt= t('.cost')
          - @statistics.costs_per_day.each do |name, cost_per_day|
            %dd= "#{name}: #{human_number(cost_per_day * 365)} €/a"
          %dt= t('.consumption')
          - @statistics.consumptions_per_day.each do |fuel, consumption_per_day|
            %dd= "#{human_number consumption_per_day * 365} #{fuel.unit}/a"
          %dt= t('.distance')
          %dd= "#{human_number(@statistics.distance_per_day * 365)} km/a"