config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  root 'car_logs#new'

  resources :cars, only: [:new, :create, :edit, :update, :index, :destroy] do
    member do
      get 'summary'
    end

    resources :fuels, only: [:create, :update, :destroy], controller: 'cars_fuels'
  end

  resources :car_logs, only: [:new, :create, :index, :show] do
    resources :refuels, only: [:new]
  end

  resources :fuels, only: [:new, :create, :edit, :update, :index, :destroy]

  resources :refuels, only: [:edit, :create, :update, :destroy]

  get '/login', to: 'sessions#new'
  match '/auth/:provider/callback', to: 'sessions#create', via: [:post, :get]
  get '/logout', to: 'sessions#destroy'
  get '/no_session', to: 'sessions#missing'
  get '/no_privileges', to: 'sessions#insufficient'
end

app/models/fuel.rb
# frozen_string_literal: true

class Fuel < ApplicationRecord
  validates :name, presence: true
  validates :unit, presence: true

  # Whether or not this application is able to pull statistics about this fuel
  # from an automated meter.
  def meterable?
    unit == 'kWh'
  end
end

app/controllers/fuels_controller.rb
# frozen_string_literal: true
class FuelsController < ApplicationController
  def new
    @fuel = Fuel.new
    render :edit
  end

  def edit
    @fuel = Fuel.find(params[:id])
  end

  def index
    @fuels = Fuel.order(:name)
  end

  def create
    fuel = Fuel.create(fuel_params)
    if fuel.persisted?
      flash[:success] = I18n.t('flashs.created_model',
                               model: Fuel.model_name.human)
    else
      helpers.flash_errors(fuel.errors)
    end
    redirect_to action: :index
  end

  def update
    fuel = Fuel.find(params[:id])
    if fuel.update(fuel_params)
      flash[:success] = I18n.t('flashs.updated_model',
                               model: Fuel.model_name.human)
    else
      helpers.flash_errors(fuel.errors)
    end

    redirect_to action: :index
  end

  def destroy
    Fuel.find(params[:id]).destroy
    flash[:success] = I18n.t('flashs.destroyed_model',
                             model: Fuel.model_name.human)
    redirect_to action: :index
  end

  private

  def fuel_params
    params.require(:fuel).permit(:name, :unit)
  end
end

app/views/fuels/edit.html.haml
.panel.panel-default
  .panel-heading
    - if @fuel.new_record?
      = I18n.t('titles.new_model', model: Fuel.model_name.human)
    - else
      = I18n.t('titles.edit_model', model: Fuel.model_name.human)
  .panel-body
    = form_for @fuel do |f|
      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control'

      .form-group
        = f.label :unit
        = f.text_field :unit, class: 'form-control'

      = f.submit I18n.t('buttons.save'), class: 'btn btn-success'

- unless @fuel.new_record?
  .panel.panel-danger
    .panel-heading
      = I18n.t('titles.destroy_model', model: Fuel.model_name.human)
    .panel-body
      = link_to I18n.t('buttons.delete'), fuel_path(@fuel),
                method: :delete,
                class: 'btn btn-danger btn-sm',
                data: { confirm: I18n.t('confirm_delete_named', name: @fuel.name) }

app/views/fuels/index.html.haml
%h1= Fuel.model_name.human(count: 2)

%table.table
  %thead
    %tr
      %th= Fuel.human_attribute_name(:name)
      %th= I18n.t('action_column')

  - @fuels.each do |fuel|
    %tr
      %td= fuel.name
      %td
        %a.btn.btn-default{href: edit_fuel_path(fuel)}
          = I18n.t('buttons.edit')

.row
  .col-md-2
    %a.btn.btn-success{href: new_fuel_path}
      = I18n.t('buttons.create_model', model: Fuel.model_name.human)